### ISSUE TITLE
Transition to Extension as Chrome Apps are soon to lose support

### ISSUE THREAD

**Issue by j9ac9k** [jomurgel/PocketCaster#3]
As the subject says, chrome has announced they will be phasing out support for chrome apps:

https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Is there an intention to transition PocketCaster to a chrome extension?

**Comment by HarrisJT** [comment]
What would be the function of the app over the website if not a standalone client?

**Comment by jomurgel** [comment]
@j9ac9k @HarrisJT I think to have an extension sort of defeats the purpose of the app.

That said, I am looking into Windows, MacOS, and Linux standalone options, perhaps built on [Electron](https://electron.atom.io/), since it's pretty clear that Shifty Jelly doesn't plan on rolling out a desktop app of their own anytime soon.  May just be a matter of time and the perceived need to get that done.

**Comment by jomurgel** [comment]
Working on new Electron-based app [here](https://github.com/jomurgel/PocketCasterApp) which may offer a good alternative.

**Comment by j9ac9k** [comment]
@jomurgel I don't have any JS/Electron experience, I've used the Qt framework some for desktops in the past, so I can't offer Electron based suggestions.  Thanks for the continued product development
